syntax = "proto3";

package campaign;

service CampaignService {
  rpc CreateCampaign(CreateCampaignRequest) returns (CreateCampaignResponse);
  rpc GetCampaigns(GetCampaignsRequest) returns (GetCampaignsResponse);
}

message CampaignRecipientInput {
  string email = 1;
  string subject = 2;
  string message = 3;
}

message CreateCampaignRequest {
  string userId = 1;
  string name = 2;
  string scheduledAt = 3;
  repeated CampaignRecipientInput recipients = 4;
}

message GetCampaignsRequest {
  string userId = 1;
}

message CampaignRecipient {
  reserved 8, 10;
  reserved "error", "updatedAt";

  string id = 1;
  string campaignId = 2;
  string email = 3;
  string subject = 4;
  string message = 5;
  string status = 6;
  string sentAt = 7;
  string createdAt = 9;
}

message Campaign {
  reserved 7;
  reserved "updatedAt";

  string id = 1;
  string userId = 2;
  string name = 3;
  string scheduledAt = 4;
  string status = 5;
  string createdAt = 6;
  repeated CampaignRecipient recipients = 8;
}

message CreateCampaignResponse {
  Campaign campaign = 1;
}

message GetCampaignsResponse {
  repeated Campaign campaigns = 1;
}
